package com.dao;

import com.modelo.Asignatura;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 * Manages data persistence for Asignatura objects.
 * @author AutoGenerated
 */
public class AsignaturaDAO {
    private String archivo = "asignaturas.dat";

    /**
     * Saves a new Asignatura to the data file.
     * @param asignatura The Asignatura object to save.
     * @throws IOException If an I/O error occurs during writing.
     * @throws ClassNotFoundException If the class of a serialized object cannot be found.
     */
    public void guardarAsignatura(Asignatura asignatura) throws IOException, ClassNotFoundException {
        File fileHandle = new File(archivo);
        ArrayList<Asignatura> lista;

        if (fileHandle.exists() && fileHandle.length() > 0) { // Check if file exists and is not empty
            FileInputStream fis = new FileInputStream(fileHandle);
            ObjectInputStream ois = new ObjectInputStream(fis);
            lista = (ArrayList<Asignatura>) ois.readObject();
            ois.close();
            fis.close();
        } else {
            lista = new ArrayList<>();
        }
        
        lista.add(asignatura);
        
        FileOutputStream fos = new FileOutputStream(archivo);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        oos.writeObject(lista);
        oos.close();
        fos.close();
    }

    /**
     * Retrieves all Asignatura objects from the data file.
     * @return An ArrayList of Asignatura objects.
     * @throws IOException If an I/O error occurs during reading (except FileNotFoundException).
     * @throws ClassNotFoundException If the class of a serialized object cannot be found.
     */
    public ArrayList<Asignatura> listarAsignaturas() throws IOException, ClassNotFoundException {
        File fileHandle = new File(archivo);
        
        if (!fileHandle.exists() || fileHandle.length() == 0) { // Check if file doesn't exist or is empty
            return new ArrayList<>(); // Return empty list if file not found or empty
        }
        
        FileInputStream fis = new FileInputStream(archivo);
        ObjectInputStream ois = new ObjectInputStream(fis);
        ArrayList<Asignatura> lista = (ArrayList<Asignatura>) ois.readObject();
        ois.close();
        fis.close();
        return lista;
    }

    /**
     * Overwrites the existing asignatura data file with the provided list of asignaturas.
     * @param asignaturas The new list of asignaturas to save.
     * @throws IOException If an I/O error occurs during writing.
     */
    public void actualizarListaAsignaturas(ArrayList<Asignatura> asignaturas) throws IOException {
        try (ObjectOutputStream salida = new ObjectOutputStream(new FileOutputStream(archivo))) {
            salida.writeObject(asignaturas);
        }
    }
}
