package com.dao;

import com.modelo.Profesor;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 * Manages data persistence for Profesor objects.
 * @author AutoGenerated
 */
public class ProfesorDAO {
    private String archivo = "profesores.dat";

    /**
     * Saves a new Profesor to the data file.
     * @param prof The Profesor object to save.
     * @throws IOException If an I/O error occurs during writing.
     * @throws ClassNotFoundException If the class of a serialized object cannot be found.
     */
    public void guardarProfesor(Profesor prof) throws IOException, ClassNotFoundException {
        File fileHandle = new File(archivo);
        ArrayList<Profesor> lista;

        if (fileHandle.exists() && fileHandle.length() > 0) { // Check if file exists and is not empty
            FileInputStream fis = new FileInputStream(fileHandle);
            ObjectInputStream ois = new ObjectInputStream(fis);
            lista = (ArrayList<Profesor>) ois.readObject();
            ois.close();
            fis.close();
        } else {
            lista = new ArrayList<>();
        }
        
        lista.add(prof);
        
        FileOutputStream fos = new FileOutputStream(archivo);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        oos.writeObject(lista);
        oos.close();
        fos.close();
    }

    /**
     * Retrieves all Profesor objects from the data file.
     * @return An ArrayList of Profesor objects.
     * @throws IOException If an I/O error occurs during reading (except FileNotFoundException).
     * @throws ClassNotFoundException If the class of a serialized object cannot be found.
     */
    public ArrayList<Profesor> listarProfesores() throws IOException, ClassNotFoundException {
        File fileHandle = new File(archivo);
        
        if (!fileHandle.exists() || fileHandle.length() == 0) { // Check if file doesn't exist or is empty
            return new ArrayList<>(); // Return empty list if file not found or empty
        }
        
        FileInputStream fis = new FileInputStream(archivo);
        ObjectInputStream ois = new ObjectInputStream(fis);
        ArrayList<Profesor> lista = (ArrayList<Profesor>) ois.readObject();
        ois.close();
        fis.close();
        return lista;
    }

    /**
     * Overwrites the existing professor data file with the provided list of professors.
     * @param profesores The new list of professors to save.
     * @throws IOException If an I/O error occurs during writing.
     */
    public void actualizarListaProfesores(ArrayList<Profesor> profesores) throws IOException {
        try (ObjectOutputStream salida = new ObjectOutputStream(new FileOutputStream(archivo))) {
            salida.writeObject(profesores);
        }
    }
}
